FROM maven:latest as builder

WORKDIR /app

COPY ./pom.xml .
COPY ./src ./src

RUN mvn test

RUN mvn package

FROM openjdk:latest

WORKDIR /app

COPY --from=builder /app/target/nombre-del-artifact.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]